// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Inventory.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BankAccountModel
    {
        /// <summary>
        /// Initializes a new instance of the BankAccountModel class.
        /// </summary>
        public BankAccountModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BankAccountModel class.
        /// </summary>
        public BankAccountModel(string bank = default(string), string bic = default(string), string iban = default(string))
        {
            Bank = bank;
            Bic = bic;
            Iban = iban;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bank")]
        public string Bank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bic")]
        public string Bic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iban")]
        public string Iban { get; set; }

    }
}
