// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Inventory.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for InventoryPropertiesPost operation.
    /// </summary>
    public partial class InventoryPropertiesPostHeaders
    {
        /// <summary>
        /// Initializes a new instance of the InventoryPropertiesPostHeaders
        /// class.
        /// </summary>
        public InventoryPropertiesPostHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InventoryPropertiesPostHeaders
        /// class.
        /// </summary>
        /// <param name="location">The location of the created
        /// resource.</param>
        public InventoryPropertiesPostHeaders(string location = default(string))
        {
            Location = location;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the location of the created resource.
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

    }
}
