version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime
    versions:
    - 5.0.2
    - 5.0.5
  - dependency-name: Npgsql.EntityFrameworkCore.PostgreSQL
    versions:
    - 5.0.2
    - 5.0.5
  - dependency-name: Blazorise.Bootstrap
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.3
    - 0.9.3.4
  - dependency-name: Blazorise.Icons.FontAwesome
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.3
    - 0.9.3.4
  - dependency-name: SonarAnalyzer.CSharp
    versions:
    - 8.17.0.26580
    - 8.18.0.27296
    - 8.19.0.28253
    - 8.20.0.28934
  - dependency-name: Microsoft.AspNetCore.Authentication.OpenIdConnect
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.DataProtection.Abstractions
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Components.Analyzers
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: NLog
    versions:
    - 4.7.7
    - 4.7.8
  - dependency-name: NLog.Web.AspNetCore
    versions:
    - 4.10.0
    - 4.11.0
  - dependency-name: IdentityModel
    versions:
    - 5.0.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
