// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssignedUnitModel
    {
        /// <summary>
        /// Initializes a new instance of the AssignedUnitModel class.
        /// </summary>
        public AssignedUnitModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssignedUnitModel class.
        /// </summary>
        /// <param name="unit">The assigned unit</param>
        public AssignedUnitModel(EmbeddedUnitModel unit)
        {
            Unit = unit;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the assigned unit
        /// </summary>
        [JsonProperty(PropertyName = "unit")]
        public EmbeddedUnitModel Unit { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Unit == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Unit");
            }
            if (Unit != null)
            {
                Unit.Validate();
            }
        }
    }
}
