// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for BlockStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BlockStatus
    {
        [EnumMember(Value = "Tentative")]
        Tentative,
        [EnumMember(Value = "Definite")]
        Definite,
        [EnumMember(Value = "Canceled")]
        Canceled
    }
    internal static class BlockStatusEnumExtension
    {
        internal static string ToSerializedValue(this BlockStatus? value)
        {
            return value == null ? null : ((BlockStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this BlockStatus value)
        {
            switch( value )
            {
                case BlockStatus.Tentative:
                    return "Tentative";
                case BlockStatus.Definite:
                    return "Definite";
                case BlockStatus.Canceled:
                    return "Canceled";
            }
            return null;
        }

        internal static BlockStatus? ParseBlockStatus(this string value)
        {
            switch( value )
            {
                case "Tentative":
                    return BlockStatus.Tentative;
                case "Definite":
                    return BlockStatus.Definite;
                case "Canceled":
                    return BlockStatus.Canceled;
            }
            return null;
        }
    }
}
