// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BlockModel
    {
        /// <summary>
        /// Initializes a new instance of the BlockModel class.
        /// </summary>
        public BlockModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BlockModel class.
        /// </summary>
        /// <param name="id">Block id</param>
        /// <param name="status">Status of the block. Tentative will just mark
        /// inventory as requested, but still allows to sell it
        /// through other channels. Definite will block the inventory for
        /// selling through other channels. Possible values include:
        /// 'Tentative', 'Definite', 'Canceled'</param>
        /// <param name="fromProperty">Start date and time from which the
        /// inventory will be blocked&lt;br /&gt;A date and time (without
        /// fractional second part) in UTC or with UTC offset as defined in
        /// &lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&gt;ISO8601:2004&lt;/a&gt;</param>
        /// <param name="to">End date and time until which the inventory will
        /// be blocked&lt;br /&gt;A date and time (without fractional second
        /// part) in UTC or with UTC offset as defined in &lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&gt;ISO8601:2004&lt;/a&gt;</param>
        /// <param name="pickedReservations">Number of reservations already
        /// picked from this block</param>
        /// <param name="created">Date of creation&lt;br /&gt;A date and time
        /// (without fractional second part) in UTC or with UTC offset as
        /// defined in &lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&gt;ISO8601:2004&lt;/a&gt;</param>
        /// <param name="modified">Date of last modification&lt;br /&gt;A date
        /// and time (without fractional second part) in UTC or with UTC offset
        /// as defined in &lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&gt;ISO8601:2004&lt;/a&gt;</param>
        /// <param name="promoCode">The promo code associated with a certain
        /// special offer used to create the block</param>
        /// <param name="corporateCode">The corporate code associated with a
        /// certain special offer used to create the block</param>
        /// <param name="timeSlices">The list of time slices for this
        /// block</param>
        /// <param name="actions">The list of actions for this block</param>
        public BlockModel(string id, EmbeddedGroupModel group, BlockStatus status, EmbeddedPropertyModel property, EmbeddedRatePlanModel ratePlan, EmbeddedUnitGroupModel unitGroup, MonetaryValueModel grossDailyRate, System.DateTime fromProperty, System.DateTime to, int pickedReservations, System.DateTime created, System.DateTime modified, string promoCode = default(string), string corporateCode = default(string), IList<BlockTimeSliceModel> timeSlices = default(IList<BlockTimeSliceModel>), IList<ActionModelBlockActionNotAllowedBlockActionReason> actions = default(IList<ActionModelBlockActionNotAllowedBlockActionReason>))
        {
            Id = id;
            Group = group;
            Status = status;
            Property = property;
            RatePlan = ratePlan;
            UnitGroup = unitGroup;
            GrossDailyRate = grossDailyRate;
            FromProperty = fromProperty;
            To = to;
            PickedReservations = pickedReservations;
            PromoCode = promoCode;
            CorporateCode = corporateCode;
            Created = created;
            Modified = modified;
            TimeSlices = timeSlices;
            Actions = actions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets block id
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "group")]
        public EmbeddedGroupModel Group { get; set; }

        /// <summary>
        /// Gets or sets status of the block. Tentative will just mark
        /// inventory as requested, but still allows to sell it
        /// through other channels. Definite will block the inventory for
        /// selling through other channels. Possible values include:
        /// 'Tentative', 'Definite', 'Canceled'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public BlockStatus Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "property")]
        public EmbeddedPropertyModel Property { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ratePlan")]
        public EmbeddedRatePlanModel RatePlan { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitGroup")]
        public EmbeddedUnitGroupModel UnitGroup { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grossDailyRate")]
        public MonetaryValueModel GrossDailyRate { get; set; }

        /// <summary>
        /// Gets or sets start date and time from which the inventory will be
        /// blocked&amp;lt;br /&amp;gt;A date and time (without fractional
        /// second part) in UTC or with UTC offset as defined in &amp;lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&amp;gt;ISO8601:2004&amp;lt;/a&amp;gt;
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public System.DateTime FromProperty { get; set; }

        /// <summary>
        /// Gets or sets end date and time until which the inventory will be
        /// blocked&amp;lt;br /&amp;gt;A date and time (without fractional
        /// second part) in UTC or with UTC offset as defined in &amp;lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&amp;gt;ISO8601:2004&amp;lt;/a&amp;gt;
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public System.DateTime To { get; set; }

        /// <summary>
        /// Gets or sets number of reservations already picked from this block
        /// </summary>
        [JsonProperty(PropertyName = "pickedReservations")]
        public int PickedReservations { get; set; }

        /// <summary>
        /// Gets or sets the promo code associated with a certain special offer
        /// used to create the block
        /// </summary>
        [JsonProperty(PropertyName = "promoCode")]
        public string PromoCode { get; set; }

        /// <summary>
        /// Gets or sets the corporate code associated with a certain special
        /// offer used to create the block
        /// </summary>
        [JsonProperty(PropertyName = "corporateCode")]
        public string CorporateCode { get; set; }

        /// <summary>
        /// Gets or sets date of creation&amp;lt;br /&amp;gt;A date and time
        /// (without fractional second part) in UTC or with UTC offset as
        /// defined in &amp;lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&amp;gt;ISO8601:2004&amp;lt;/a&amp;gt;
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime Created { get; set; }

        /// <summary>
        /// Gets or sets date of last modification&amp;lt;br /&amp;gt;A date
        /// and time (without fractional second part) in UTC or with UTC offset
        /// as defined in &amp;lt;a
        /// href="https://en.wikipedia.org/wiki/ISO_8601"&amp;gt;ISO8601:2004&amp;lt;/a&amp;gt;
        /// </summary>
        [JsonProperty(PropertyName = "modified")]
        public System.DateTime Modified { get; set; }

        /// <summary>
        /// Gets or sets the list of time slices for this block
        /// </summary>
        [JsonProperty(PropertyName = "timeSlices")]
        public IList<BlockTimeSliceModel> TimeSlices { get; set; }

        /// <summary>
        /// Gets or sets the list of actions for this block
        /// </summary>
        [JsonProperty(PropertyName = "actions")]
        public IList<ActionModelBlockActionNotAllowedBlockActionReason> Actions { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (Group == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Group");
            }
            if (Property == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Property");
            }
            if (RatePlan == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RatePlan");
            }
            if (UnitGroup == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UnitGroup");
            }
            if (GrossDailyRate == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "GrossDailyRate");
            }
            if (Group != null)
            {
                Group.Validate();
            }
            if (Property != null)
            {
                Property.Validate();
            }
            if (RatePlan != null)
            {
                RatePlan.Validate();
            }
            if (UnitGroup != null)
            {
                UnitGroup.Validate();
            }
            if (GrossDailyRate != null)
            {
                GrossDailyRate.Validate();
            }
            if (TimeSlices != null)
            {
                foreach (var element in TimeSlices)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (Actions != null)
            {
                foreach (var element1 in Actions)
                {
                    if (element1 != null)
                    {
                        element1.Validate();
                    }
                }
            }
        }
    }
}
