// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BlockListModel
    {
        /// <summary>
        /// Initializes a new instance of the BlockListModel class.
        /// </summary>
        public BlockListModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BlockListModel class.
        /// </summary>
        /// <param name="blocks">List of blocks</param>
        /// <param name="count">Total count of items</param>
        public BlockListModel(IList<BlockItemModel> blocks, long count)
        {
            Blocks = blocks;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of blocks
        /// </summary>
        [JsonProperty(PropertyName = "blocks")]
        public IList<BlockItemModel> Blocks { get; set; }

        /// <summary>
        /// Gets or sets total count of items
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long Count { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Blocks == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Blocks");
            }
            if (Blocks != null)
            {
                foreach (var element in Blocks)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
