// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ChannelCode.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ChannelCode
    {
        [EnumMember(Value = "Direct")]
        Direct,
        [EnumMember(Value = "BookingCom")]
        BookingCom,
        [EnumMember(Value = "Ibe")]
        Ibe,
        [EnumMember(Value = "ChannelManager")]
        ChannelManager,
        [EnumMember(Value = "Expedia")]
        Expedia
    }
    internal static class ChannelCodeEnumExtension
    {
        internal static string ToSerializedValue(this ChannelCode? value)
        {
            return value == null ? null : ((ChannelCode)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ChannelCode value)
        {
            switch( value )
            {
                case ChannelCode.Direct:
                    return "Direct";
                case ChannelCode.BookingCom:
                    return "BookingCom";
                case ChannelCode.Ibe:
                    return "Ibe";
                case ChannelCode.ChannelManager:
                    return "ChannelManager";
                case ChannelCode.Expedia:
                    return "Expedia";
            }
            return null;
        }

        internal static ChannelCode? ParseChannelCode(this string value)
        {
            switch( value )
            {
                case "Direct":
                    return ChannelCode.Direct;
                case "BookingCom":
                    return ChannelCode.BookingCom;
                case "Ibe":
                    return ChannelCode.Ibe;
                case "ChannelManager":
                    return ChannelCode.ChannelManager;
                case "Expedia":
                    return ChannelCode.Expedia;
            }
            return null;
        }
    }
}
