// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for NotAllowedReservationActionReason.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum NotAllowedReservationActionReason
    {
        [EnumMember(Value = "CheckInNotAllowedForReservationNotInStatusConfirmed")]
        CheckInNotAllowedForReservationNotInStatusConfirmed,
        [EnumMember(Value = "CheckInNotAllowedBeforeArrivalDate")]
        CheckInNotAllowedBeforeArrivalDate,
        [EnumMember(Value = "CheckInNotAllowedAfterDepartureDateTime")]
        CheckInNotAllowedAfterDepartureDateTime,
        [EnumMember(Value = "CheckInNotAllowedWithoutUnitAssignedForWholeStay")]
        CheckInNotAllowedWithoutUnitAssignedForWholeStay,
        [EnumMember(Value = "CheckOutNotAllowedForReservationNotInStatusInHouse")]
        CheckOutNotAllowedForReservationNotInStatusInHouse,
        [EnumMember(Value = "CheckOutNotAllowedForPastReservationNotInStatusConfirmedOrInHouse")]
        CheckOutNotAllowedForPastReservationNotInStatusConfirmedOrInHouse,
        [EnumMember(Value = "CheckOutNotAllowedWithDepartureDateMoreThanOneDayInTheFuture")]
        CheckOutNotAllowedWithDepartureDateMoreThanOneDayInTheFuture,
        [EnumMember(Value = "CancelNotAllowedForReservationNotInStatusConfirmed")]
        CancelNotAllowedForReservationNotInStatusConfirmed,
        [EnumMember(Value = "AmendNotAllowedForNotAmendableTimeSlices")]
        AmendNotAllowedForNotAmendableTimeSlices,
        [EnumMember(Value = "AmendArrivalNotAllowedForReservationNotInStatusConfirmed")]
        AmendArrivalNotAllowedForReservationNotInStatusConfirmed,
        [EnumMember(Value = "AmendArrivalNotAllowedForArrivalInThePast")]
        AmendArrivalNotAllowedForArrivalInThePast,
        [EnumMember(Value = "AmendDepartureNotAllowedForReservationNotInStatusConfirmedOrInHouse")]
        AmendDepartureNotAllowedForReservationNotInStatusConfirmedOrInHouse,
        [EnumMember(Value = "AmendDepartureNotAllowedForReservationDepartureDateTooFarInThePast")]
        AmendDepartureNotAllowedForReservationDepartureDateTooFarInThePast,
        [EnumMember(Value = "NoShowNotAllowedForReservationNotInStatusConfirmed")]
        NoShowNotAllowedForReservationNotInStatusConfirmed,
        [EnumMember(Value = "NoShowNotAllowedBeforeArrivalDate")]
        NoShowNotAllowedBeforeArrivalDate,
        [EnumMember(Value = "AssignUnitNotAllowedForReservationInThePast")]
        AssignUnitNotAllowedForReservationInThePast,
        [EnumMember(Value = "AssignUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse")]
        AssignUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse,
        [EnumMember(Value = "UnassignUnitNotAllowedForReservationInThePast")]
        UnassignUnitNotAllowedForReservationInThePast,
        [EnumMember(Value = "UnassignUnitNotAllowedForReservationNotInStatusConfirmed")]
        UnassignUnitNotAllowedForReservationNotInStatusConfirmed,
        [EnumMember(Value = "UnassignUnitNotAllowedForReservationWithoutUnit")]
        UnassignUnitNotAllowedForReservationWithoutUnit
    }
    internal static class NotAllowedReservationActionReasonEnumExtension
    {
        internal static string ToSerializedValue(this NotAllowedReservationActionReason? value)
        {
            return value == null ? null : ((NotAllowedReservationActionReason)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this NotAllowedReservationActionReason value)
        {
            switch( value )
            {
                case NotAllowedReservationActionReason.CheckInNotAllowedForReservationNotInStatusConfirmed:
                    return "CheckInNotAllowedForReservationNotInStatusConfirmed";
                case NotAllowedReservationActionReason.CheckInNotAllowedBeforeArrivalDate:
                    return "CheckInNotAllowedBeforeArrivalDate";
                case NotAllowedReservationActionReason.CheckInNotAllowedAfterDepartureDateTime:
                    return "CheckInNotAllowedAfterDepartureDateTime";
                case NotAllowedReservationActionReason.CheckInNotAllowedWithoutUnitAssignedForWholeStay:
                    return "CheckInNotAllowedWithoutUnitAssignedForWholeStay";
                case NotAllowedReservationActionReason.CheckOutNotAllowedForReservationNotInStatusInHouse:
                    return "CheckOutNotAllowedForReservationNotInStatusInHouse";
                case NotAllowedReservationActionReason.CheckOutNotAllowedForPastReservationNotInStatusConfirmedOrInHouse:
                    return "CheckOutNotAllowedForPastReservationNotInStatusConfirmedOrInHouse";
                case NotAllowedReservationActionReason.CheckOutNotAllowedWithDepartureDateMoreThanOneDayInTheFuture:
                    return "CheckOutNotAllowedWithDepartureDateMoreThanOneDayInTheFuture";
                case NotAllowedReservationActionReason.CancelNotAllowedForReservationNotInStatusConfirmed:
                    return "CancelNotAllowedForReservationNotInStatusConfirmed";
                case NotAllowedReservationActionReason.AmendNotAllowedForNotAmendableTimeSlices:
                    return "AmendNotAllowedForNotAmendableTimeSlices";
                case NotAllowedReservationActionReason.AmendArrivalNotAllowedForReservationNotInStatusConfirmed:
                    return "AmendArrivalNotAllowedForReservationNotInStatusConfirmed";
                case NotAllowedReservationActionReason.AmendArrivalNotAllowedForArrivalInThePast:
                    return "AmendArrivalNotAllowedForArrivalInThePast";
                case NotAllowedReservationActionReason.AmendDepartureNotAllowedForReservationNotInStatusConfirmedOrInHouse:
                    return "AmendDepartureNotAllowedForReservationNotInStatusConfirmedOrInHouse";
                case NotAllowedReservationActionReason.AmendDepartureNotAllowedForReservationDepartureDateTooFarInThePast:
                    return "AmendDepartureNotAllowedForReservationDepartureDateTooFarInThePast";
                case NotAllowedReservationActionReason.NoShowNotAllowedForReservationNotInStatusConfirmed:
                    return "NoShowNotAllowedForReservationNotInStatusConfirmed";
                case NotAllowedReservationActionReason.NoShowNotAllowedBeforeArrivalDate:
                    return "NoShowNotAllowedBeforeArrivalDate";
                case NotAllowedReservationActionReason.AssignUnitNotAllowedForReservationInThePast:
                    return "AssignUnitNotAllowedForReservationInThePast";
                case NotAllowedReservationActionReason.AssignUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse:
                    return "AssignUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse";
                case NotAllowedReservationActionReason.UnassignUnitNotAllowedForReservationInThePast:
                    return "UnassignUnitNotAllowedForReservationInThePast";
                case NotAllowedReservationActionReason.UnassignUnitNotAllowedForReservationNotInStatusConfirmed:
                    return "UnassignUnitNotAllowedForReservationNotInStatusConfirmed";
                case NotAllowedReservationActionReason.UnassignUnitNotAllowedForReservationWithoutUnit:
                    return "UnassignUnitNotAllowedForReservationWithoutUnit";
            }
            return null;
        }

        internal static NotAllowedReservationActionReason? ParseNotAllowedReservationActionReason(this string value)
        {
            switch( value )
            {
                case "CheckInNotAllowedForReservationNotInStatusConfirmed":
                    return NotAllowedReservationActionReason.CheckInNotAllowedForReservationNotInStatusConfirmed;
                case "CheckInNotAllowedBeforeArrivalDate":
                    return NotAllowedReservationActionReason.CheckInNotAllowedBeforeArrivalDate;
                case "CheckInNotAllowedAfterDepartureDateTime":
                    return NotAllowedReservationActionReason.CheckInNotAllowedAfterDepartureDateTime;
                case "CheckInNotAllowedWithoutUnitAssignedForWholeStay":
                    return NotAllowedReservationActionReason.CheckInNotAllowedWithoutUnitAssignedForWholeStay;
                case "CheckOutNotAllowedForReservationNotInStatusInHouse":
                    return NotAllowedReservationActionReason.CheckOutNotAllowedForReservationNotInStatusInHouse;
                case "CheckOutNotAllowedForPastReservationNotInStatusConfirmedOrInHouse":
                    return NotAllowedReservationActionReason.CheckOutNotAllowedForPastReservationNotInStatusConfirmedOrInHouse;
                case "CheckOutNotAllowedWithDepartureDateMoreThanOneDayInTheFuture":
                    return NotAllowedReservationActionReason.CheckOutNotAllowedWithDepartureDateMoreThanOneDayInTheFuture;
                case "CancelNotAllowedForReservationNotInStatusConfirmed":
                    return NotAllowedReservationActionReason.CancelNotAllowedForReservationNotInStatusConfirmed;
                case "AmendNotAllowedForNotAmendableTimeSlices":
                    return NotAllowedReservationActionReason.AmendNotAllowedForNotAmendableTimeSlices;
                case "AmendArrivalNotAllowedForReservationNotInStatusConfirmed":
                    return NotAllowedReservationActionReason.AmendArrivalNotAllowedForReservationNotInStatusConfirmed;
                case "AmendArrivalNotAllowedForArrivalInThePast":
                    return NotAllowedReservationActionReason.AmendArrivalNotAllowedForArrivalInThePast;
                case "AmendDepartureNotAllowedForReservationNotInStatusConfirmedOrInHouse":
                    return NotAllowedReservationActionReason.AmendDepartureNotAllowedForReservationNotInStatusConfirmedOrInHouse;
                case "AmendDepartureNotAllowedForReservationDepartureDateTooFarInThePast":
                    return NotAllowedReservationActionReason.AmendDepartureNotAllowedForReservationDepartureDateTooFarInThePast;
                case "NoShowNotAllowedForReservationNotInStatusConfirmed":
                    return NotAllowedReservationActionReason.NoShowNotAllowedForReservationNotInStatusConfirmed;
                case "NoShowNotAllowedBeforeArrivalDate":
                    return NotAllowedReservationActionReason.NoShowNotAllowedBeforeArrivalDate;
                case "AssignUnitNotAllowedForReservationInThePast":
                    return NotAllowedReservationActionReason.AssignUnitNotAllowedForReservationInThePast;
                case "AssignUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse":
                    return NotAllowedReservationActionReason.AssignUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse;
                case "UnassignUnitNotAllowedForReservationInThePast":
                    return NotAllowedReservationActionReason.UnassignUnitNotAllowedForReservationInThePast;
                case "UnassignUnitNotAllowedForReservationNotInStatusConfirmed":
                    return NotAllowedReservationActionReason.UnassignUnitNotAllowedForReservationNotInStatusConfirmed;
                case "UnassignUnitNotAllowedForReservationWithoutUnit":
                    return NotAllowedReservationActionReason.UnassignUnitNotAllowedForReservationWithoutUnit;
            }
            return null;
        }
    }
}
