// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PersonCompanyModel
    {
        /// <summary>
        /// Initializes a new instance of the PersonCompanyModel class.
        /// </summary>
        public PersonCompanyModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PersonCompanyModel class.
        /// </summary>
        /// <param name="name">Name of the company</param>
        /// <param name="taxId">Tax or Vat ID of the company</param>
        public PersonCompanyModel(string name = default(string), string taxId = default(string))
        {
            Name = name;
            TaxId = taxId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets name of the company
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets tax or Vat ID of the company
        /// </summary>
        [JsonProperty(PropertyName = "taxId")]
        public string TaxId { get; set; }

    }
}
