// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for PricingMode.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PricingMode
    {
        [EnumMember(Value = "Included")]
        Included,
        [EnumMember(Value = "Additional")]
        Additional
    }
    internal static class PricingModeEnumExtension
    {
        internal static string ToSerializedValue(this PricingMode? value)
        {
            return value == null ? null : ((PricingMode)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this PricingMode value)
        {
            switch( value )
            {
                case PricingMode.Included:
                    return "Included";
                case PricingMode.Additional:
                    return "Additional";
            }
            return null;
        }

        internal static PricingMode? ParsePricingMode(this string value)
        {
            switch( value )
            {
                case "Included":
                    return PricingMode.Included;
                case "Additional":
                    return PricingMode.Additional;
            }
            return null;
        }
    }
}
