// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for PricedUnit.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PricedUnit
    {
        [EnumMember(Value = "Room")]
        Room,
        [EnumMember(Value = "Person")]
        Person
    }
    internal static class PricedUnitEnumExtension
    {
        internal static string ToSerializedValue(this PricedUnit? value)
        {
            return value == null ? null : ((PricedUnit)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this PricedUnit value)
        {
            switch( value )
            {
                case PricedUnit.Room:
                    return "Room";
                case PricedUnit.Person:
                    return "Person";
            }
            return null;
        }

        internal static PricedUnit? ParsePricedUnit(this string value)
        {
            switch( value )
            {
                case "Room":
                    return PricedUnit.Room;
                case "Person":
                    return PricedUnit.Person;
            }
            return null;
        }
    }
}
