// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PropertyValueModel
    {
        /// <summary>
        /// Initializes a new instance of the PropertyValueModel class.
        /// </summary>
        public PropertyValueModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PropertyValueModel class.
        /// </summary>
        /// <param name="balance">The balance of this booking for this
        /// property</param>
        /// <param name="property">The property</param>
        /// <param name="totalGrossAmount">The total gross amount of this
        /// booking for this property</param>
        public PropertyValueModel(MonetaryValueModel balance, EmbeddedPropertyModel property, MonetaryValueModel totalGrossAmount)
        {
            Balance = balance;
            Property = property;
            TotalGrossAmount = totalGrossAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the balance of this booking for this property
        /// </summary>
        [JsonProperty(PropertyName = "balance")]
        public MonetaryValueModel Balance { get; set; }

        /// <summary>
        /// Gets or sets the property
        /// </summary>
        [JsonProperty(PropertyName = "property")]
        public EmbeddedPropertyModel Property { get; set; }

        /// <summary>
        /// Gets or sets the total gross amount of this booking for this
        /// property
        /// </summary>
        [JsonProperty(PropertyName = "totalGrossAmount")]
        public MonetaryValueModel TotalGrossAmount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Balance == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Balance");
            }
            if (Property == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Property");
            }
            if (TotalGrossAmount == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TotalGrossAmount");
            }
            if (Balance != null)
            {
                Balance.Validate();
            }
            if (Property != null)
            {
                Property.Validate();
            }
            if (TotalGrossAmount != null)
            {
                TotalGrossAmount.Validate();
            }
        }
    }
}
