// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReservationServiceModel
    {
        /// <summary>
        /// Initializes a new instance of the ReservationServiceModel class.
        /// </summary>
        public ReservationServiceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReservationServiceModel class.
        /// </summary>
        /// <param name="bookedAsExtra">Whether this service is already booked
        /// as extra</param>
        /// <param name="count">The count of booked services</param>
        /// <param name="serviceDate">The date this service is
        /// delivered</param>
        public ReservationServiceModel(AmountModel amount, bool bookedAsExtra, int count, EmbeddedServiceModel service, System.DateTime serviceDate)
        {
            Amount = amount;
            BookedAsExtra = bookedAsExtra;
            Count = count;
            Service = service;
            ServiceDate = serviceDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public AmountModel Amount { get; set; }

        /// <summary>
        /// Gets or sets whether this service is already booked as extra
        /// </summary>
        [JsonProperty(PropertyName = "bookedAsExtra")]
        public bool BookedAsExtra { get; set; }

        /// <summary>
        /// Gets or sets the count of booked services
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "service")]
        public EmbeddedServiceModel Service { get; set; }

        /// <summary>
        /// Gets or sets the date this service is delivered
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "serviceDate")]
        public System.DateTime ServiceDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Amount == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Amount");
            }
            if (Service == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Service");
            }
            if (Amount != null)
            {
                Amount.Validate();
            }
            if (Service != null)
            {
                Service.Validate();
            }
        }
    }
}
