// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ReservationServiceItemModel
    {
        /// <summary>
        /// Initializes a new instance of the ReservationServiceItemModel
        /// class.
        /// </summary>
        public ReservationServiceItemModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReservationServiceItemModel
        /// class.
        /// </summary>
        /// <param name="dates">The dates the service will be delivered with
        /// its price</param>
        public ReservationServiceItemModel(ServiceModel service, AmountModel totalAmount, IList<ServiceDateItemModel> dates)
        {
            Service = service;
            TotalAmount = totalAmount;
            Dates = dates;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "service")]
        public ServiceModel Service { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalAmount")]
        public AmountModel TotalAmount { get; set; }

        /// <summary>
        /// Gets or sets the dates the service will be delivered with its price
        /// </summary>
        [JsonProperty(PropertyName = "dates")]
        public IList<ServiceDateItemModel> Dates { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Service == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Service");
            }
            if (TotalAmount == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TotalAmount");
            }
            if (Dates == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Dates");
            }
            if (Service != null)
            {
                Service.Validate();
            }
            if (TotalAmount != null)
            {
                TotalAmount.Validate();
            }
            if (Dates != null)
            {
                foreach (var element in Dates)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
