// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReservationValidationMessageModel
    {
        /// <summary>
        /// Initializes a new instance of the ReservationValidationMessageModel
        /// class.
        /// </summary>
        public ReservationValidationMessageModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReservationValidationMessageModel
        /// class.
        /// </summary>
        /// <param name="category">The message category. Possible values
        /// include: 'OfferNotAvailable', 'AutoUnitAssignment'</param>
        /// <param name="code">The message Code. Possible values include:
        /// 'UnitGroupFullyBooked', 'UnitGroupCapacityExceeded',
        /// 'RatePlanRestrictionsViolated', 'RatePlanSurchargesNotSet',
        /// 'RateRestrictionsViolated', 'RatePlanChannelNotSet', 'RatesNotSet',
        /// 'BlockFullyBooked', 'UnitMoved',
        /// 'IncludedServicesAmountExceededRateAmount',
        /// 'RatePlanCompanyRestrictionsViolated'</param>
        /// <param name="message">The message description</param>
        public ReservationValidationMessageModel(ValidationMessageCategory category, ValidationMessageCode code, string message)
        {
            Category = category;
            Code = code;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the message category. Possible values include:
        /// 'OfferNotAvailable', 'AutoUnitAssignment'
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public ValidationMessageCategory Category { get; set; }

        /// <summary>
        /// Gets or sets the message Code. Possible values include:
        /// 'UnitGroupFullyBooked', 'UnitGroupCapacityExceeded',
        /// 'RatePlanRestrictionsViolated', 'RatePlanSurchargesNotSet',
        /// 'RateRestrictionsViolated', 'RatePlanChannelNotSet', 'RatesNotSet',
        /// 'BlockFullyBooked', 'UnitMoved',
        /// 'IncludedServicesAmountExceededRateAmount',
        /// 'RatePlanCompanyRestrictionsViolated'
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public ValidationMessageCode Code { get; set; }

        /// <summary>
        /// Gets or sets the message description
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Message == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Message");
            }
        }
    }
}
