// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Traces.ApaleoClients.Booking.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TravelPurpose.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TravelPurpose
    {
        [EnumMember(Value = "Business")]
        Business,
        [EnumMember(Value = "Leisure")]
        Leisure
    }
    internal static class TravelPurposeEnumExtension
    {
        internal static string ToSerializedValue(this TravelPurpose? value)
        {
            return value == null ? null : ((TravelPurpose)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this TravelPurpose value)
        {
            switch( value )
            {
                case TravelPurpose.Business:
                    return "Business";
                case TravelPurpose.Leisure:
                    return "Leisure";
            }
            return null;
        }

        internal static TravelPurpose? ParseTravelPurpose(this string value)
        {
            switch( value )
            {
                case "Business":
                    return TravelPurpose.Business;
                case "Leisure":
                    return TravelPurpose.Leisure;
            }
            return null;
        }
    }
}
